
vault:
    uri: 'http://192.168.99.100:8200'
    login-url: '/v1/auth/github/login'

jhipster:
  security:
    authentication:
      jwt:
        secret: bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl